import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "@/components/navbar/navbar";
import { Providers } from "@/utils/providers";
import { crimson, karla } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Trinity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" className="h-full">
        <body
          style={{
            gridTemplateColumns: "5rem auto",
            gridTemplateRows: "100vh",
          }}
          className={`${karla.className} ${karla.variable} ${crimson.variable} h-full antialiased vsc-initialized grid `}
        >
          <div className="col-start-1">
            <Navbar />
          </div>
          <div className="col-start-2">{children}</div>
        </body>
      </html>
    </Providers>
  );
}
