import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "@/components/navbar/navbar";
import { Providers } from "@/utils/providers";
import { crimson, karla } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Trinity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" className="h-full">
        <body
          className={`${karla.className} ${karla.variable} ${crimson.variable} antialiased vsc-initialized h-full`}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </Providers>
  );
}
