FROM node:23 AS development

WORKDIR /app

COPY package.json package-lock.json ./
RUN ls -la /app

RUN npm install

# Création de l'image de production
FROM node:23 AS production

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --production

COPY . .

EXPOSE 3002

CMD [ "npm", "run", "start" ]