# FROM node:23 AS development

# WORKDIR /app

# COPY package*.json ./

# RUN npm install

# # Création de l'image de production
# FROM node:23 AS production

# WORKDIR /app

# COPY package*.json ./
# RUN npm install --production

# COPY . .

# EXPOSE 3002

# CMD [ "npm", "run", "start" ]


FROM node:23

WORKDIR /app

# Copier les fichiers de configuration et installer les dépendances
COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3002

CMD [ "npm", "run", "dev" ]