FROM node:18

WORKDIR /app

COPY trinity/package*.json ./
COPY trinity ./

RUN npm install -g expo-cli
RUN npm install
RUN npm install -g @expo/ngrok

EXPOSE 19000 19001 19002

CMD ["npx", "expo","start", "--tunnel"]